version: "3.8"
services:
  backend:
      image: "miliariadnane/tasks-planner:22.6.2022.22.5.49"
      ports:
      - "80:8080"
      restart: "always"
      environment:
        SPRING_PROFILES_ACTIVE: dev
