version: "3.8"
services:
  backend:
      image: "miliariadnane/tasks-planner:31.5.2022.16.49.26"
      ports:
      - "80:8080"
      restart: "always"
      environment:
        SPRING_PROFILES_ACTIVE: dev
