version: "3.8"
services:
  backend:
      image: "miliariadnane/tasks-planner:24.6.2022.16.56.32"
      ports:
      - "80:8080"
      restart: "always"
      environment:
        SPRING_PROFILES_ACTIVE: dev
