version: "3.8"
services:
  backend:
      image: "miliariadnane/tasks-planner:24.6.2022.11.48.9"
      ports:
      - "80:8080"
      restart: "always"
      environment:
        SPRING_PROFILES_ACTIVE: dev
