version: "3.8"
services:
  backend:
      image: "miliariadnane/tasks-planner:5.6.2022.15.3.27"
      ports:
      - "80:8080"
      restart: "always"
      environment:
        SPRING_PROFILES_ACTIVE: dev
