version: "3.8"
services:
  backend:
      image: "miliariadnane/tasks-planner:1.6.2022.13.9.14"
      ports:
      - "80:8080"
      restart: "always"
      environment:
        SPRING_PROFILES_ACTIVE: dev
