version: "3.8"
services:
  backend:
      image: "miliariadnane/tasks-planner:23.6.2022.23.58.4"
      ports:
      - "80:8080"
      restart: "always"
      environment:
        SPRING_PROFILES_ACTIVE: dev
