name: Build CI

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  # Postgres
  POSTGRESQL_DB: tasksplanner
  POSTGRESQL_USER: postgres
  POSTGRESQL_PASSWORD: password

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.1
        env:
          POSTGRES_DB: ${{ env.POSTGRESQL_DB }}
          POSTGRES_USER: ${{ env.POSTGRESQL_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRESQL_PASSWORD }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          # Java
          java-version: '15'
          distribution: 'adopt'
          cache: maven

      - name: Maven Clean Package
        run: mvn --no-transfer-progress clean package -P build-frontend
